version: "3.9"

volumes:
  dev-postgres-data:

services:
  dev-postgres:
    container_name: dev-postgres
    image: "postgres:13.6-alpine3.15"
    env_file: ../.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - dev-postgres-data:/var/lib/postgresql/data
